global:
  scrape_interval: 10s  # Scrape every 10 seconds

scrape_configs:
  - job_name: 'postgresql'
    static_configs:
      - targets: ['dhp-postgres-exporter:9187']  # Scrape from the PostgreSQL exporter
    metrics_path: /metrics
    scheme: http

  - job_name: 'prometheus'
    static_configs:
      - targets: ['dhp-prometheus:9090']
