global:
  scrape_interval: 10s  # Use the lower interval for more frequent data collection

scrape_configs:
  # PostgreSQL Exporter
  - job_name: 'postgresql'
    static_configs:
      - targets: ['dhp-postgres-exporter:9187']
    metrics_path: /metrics
    scheme: http

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['dhp-prometheus:9090']

  # Redis Exporter Targets
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
          - redis://dhp-redis-1:6379
          - redis://dhp-redis-2:6380
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: dhp-redis-exporter-master:9121

  # Redis Master Metrics
  - job_name: 'redis_master'
    static_configs:
      - targets: ['dhp-redis-exporter-master:9121']

  # Load Balancer Metrics
  - job_name: 'load-balancer-metrics'
    static_configs:
      - targets: ['dhp-haproxy:8405']

  # Docker Monitoring (Node Exporter, cAdvisor)
  - job_name: 'docker-monitor'
    scrape_interval: 120s
    static_configs:
      - targets: ['localhost:9090', 'dhp-cadvisor:8080', 'dhp-monitoring-node-exporter:9100']
